### PR TITLE
Support relation by foreign id

### PR DESCRIPTION
**Pull request by xslim**
Currently relations are supported by searching `relationName` in `representation`

This hack allows building relations by using `relationName_id` or `relationName_ids`, as many Ruby on Rails engines return.

### CODE REVIEW

**Comment by mattt** [comment]
Thanks for your pull request, @xslim. There's a lot in here other than the foreign ID stuff, so it's going to take some time for me to determine what I should take from this. Bear with me for a moment.

**Comment by xslim** [comment]
Sorry for a lot of commits, I'm trying to use the library in current app development, and I stuccoed with the problem of entities are not saved in DB. So some of the commits are fixing this issue.

**Comment by xslim** [comment]
Also I've made implementation for sending If-Modified-Since and working with 304 Not Modified… but this work is currently in my gist https://gist.github.com/3855430

If you have any comments how to improve the code for pull request - please tell me I'll do that.

**Comment by mattt** [comment]
No worries at all—thanks for your contributions.

As it were, I _just_ added `Last-Modified` support myself, with 40bee2dfe9324210ed42c89d96095c27097284a3. It takes a different approach from yours by managing `Last-Modified` in the same way as resource identifiers. Interested to hear any thoughts you have.

**Comment by xslim** [comment]
You developed `Last-Modified` for "per-resource request"

What I did in my gist, is developed `Last-modified` when requesting "array" of items.

The example implementation on rails side is

``` ruby
#AreasController
  def index
    @areas = parent.areas
    if stale?(last_modified: @areas.max(:updated_at))
      respond_with @areas
    end
  end
```

So I get the last modified area in database, and send this info to server. Server checks it against his DB and returns just :304 if nothing changed, or :200 with the list of areas if there were changes. This saves bandwidth.

**Comment by xslim** [comment]
https://github.com/xslim/AFIncrementalStore/commit/06041256e5c76190fba714f4b6d8a4c2aff8c180 prevents crashing when server sends `304 Not-Modified` and empty data in `success`.

To make `304` a success response I also added this code in `APIClient` subclass

``` obj-c
// 304 Not-Modified
[AFJSONRequestOperation addAcceptableStatusCodes:[NSIndexSet indexSetWithIndex:304]];
```

**Comment by xslim** [comment]
Should I change my pull request to reflect your latest commits?

**Comment by mattt** [comment]
As of e8c6472bf42f763d77e5c5ca584099abd555f906, AFIncrementalStore is no longer being actively maintained. Thank you for your contributions; my sincere apologies for any inconvenience this may have caused.

**Pull request closed without merging**
