### PR TITLE
Main thread blocked by many context read/write operations 

### PR DESCRIPTION
**Pull request by ivanvc**
First, a little background about the issue. I was trying out AFIncrementalStore, and added to an existent project. This has an API call in which it fetches 40 objects, it's not a huge number, but a little bigger than the current calls made in the sample app (http://afincrementalstore-example-api.herokuapp.com).

So, I've discovered, that, as the whole AFHTTPRequestOperation is being executed in the main queue, and it enumerates the response objects with concurrency. And because Core Data operations to read/write are executed in the main queue. It was blocking it. That caused that the UI stopped working, and the fetch never finishes.

After some time debugging and trying to fix the problem. Found that if the Request Operation is executed in a secondary queue, and reading/writing to the Managed Context in the main queue, it fixes the problem. So, I've fixed it in a branch in my fork, and it works fine with my project and the sample app. I'm not an expert in NSIncerementStore, so I suggest taking a deep look at the fix, but as said everything should be working fine.

### CODE REVIEW

**Comment by mattt** [comment]
Excellent work. This goes to show the importance of developing against non-trivial examples (something which I've been admittedly slow in doing this time, so I appreciate your working through this). Thanks so much for the patch—this has all been merged into master as of 788c5e5c256ee0a6522915f25e29717f63349d5b.

**Comment by ghost** [comment]
I seem to have the similar problem now. My UI thread is unresponsive, when I execute the fetch request and when it finishes pulling it is again fine. I am using the latest version of AFIncrementalStore.

**Comment by cmezak** [comment]
Same situation as insane-36.

**Comment by JeanetteMueller** [comment]
Same Problems here.

**Pull request merged**
