### PR TITLE
Migrate the Backing Managed Object Context to use the Private Queue concurrent type.

### PR DESCRIPTION
**Pull request by pitiphong-p**
Now AFIS use Main Queue concurrent type for backing context which will be impact on UI performance. I found in 
https://github.com/AFNetworking/AFIncrementalStore/issues/37#issuecomment-8627682
that you tried to use private queue in backing context but it didn't work.

I found that if you want to use Private Queue type, you must use -[MOC performBlock:] or -[MOC performBlockAndWait:] for execute code in its private queue

for more information please see WWDC 2011 session 303

I've tried to migrate the backing context to use Private Queue type and it work properly for me now. So I think you might want this pull request. :+1:

### CODE REVIEW

**Comment by pitiphong-p** [comment]
It has the problem with backing context now. I'm looking for nit now

**Comment by pitiphong-p** [comment]
It's seem to work properly now :)

**Comment by pitiphong-p** [comment]
Well there are relationship values is disappear form from backing store in some case. I'm investingating on it now. Hope can fixed in soon.

**Comment by pitiphong-p** [comment]
It's seem to work properly now.
If you find problem please tell me :)

**Comment by mattt** [comment]
As of 836875d717cc54f09155b9d92b4051d373d3c998, all of the child contexts are using private concurrency types. Thanks to @evadne for doing a lot of the legwork around that.

**Pull request closed without merging**
