### PR TITLE
AFIncrementalStoreContextDidFetchRemoteValues Notification returns a fetch request on the backing store

### PR DESCRIPTION
**Pull request by aprato**
This stops executeFetchRequest:withContext:error: from modifying the incoming fetch request variable. Currently if you executed with managed object result type the calling code will receive a different fetch request in the AFIncrementalStoreContextDidFetchRemoteValues notification which does not match what was executed.

### CODE REVIEW

**Comment by aprato** [comment]
I've continued to have problems with the fetch request being returned from the notification even after this commit. It looks to be something happening before AFIncrementalStore. I put a breakpoint on executeRequest:withContext:error: and sometimes (random but seems to happen in streaks) I get a different fetch request here than passed in. When it's different it's different in a consistent way... the fetchLimit is fetchLimit+1.

**Comment by mattt** [comment]
> When it's different it's different in a consistent way... the fetchLimit is fetchLimit+1.

Well, you know what they say, there are two problems in programming: naming things, threading, and off-by-one errors.

Totally bizarre, that.

But you're spot-on as far as the fetch request goes—I totally missed that this was being passed further down the line. I'll merge that in now.

**Comment by mattt** [comment]
Thanks again for the patch!

Let me know if you have any more leads on the bizarre off-by-one error. Just Core Data being cheeky, maybe?

**Comment by aprato** [comment]
Good question, I'll keep you posted. For now I've worked around it. But I've also seen it pop up on my 'list' page where I set it to 10 but see the request going out to the server with limit=11.... but I'll save that for another day :smile:

**Pull request merged**
