### PR TITLE
Prevent waiting on main context while inserting new objects

### PR DESCRIPTION
**Pull request by oliland**
Why are we creating a child context with a private queue only to make our main queue wait? I know this fix seems daft, but this has solved all of my UI locking problems when making fetch requests with many relationships / many objects. It seems safe as we refresh the objects in the main context when we've finished inserting in the child context, which is what we're supposed to do. What am I missing?

### CODE REVIEW

**Comment by oliland** [comment]
I've implemented said algorithm before in a previous project. While it does improve performance greatly in some cases, it won't solve to the problem of these operations happening on the wrong thread. I would argue that we should ensure that what should be happening in the background happens in the background before changing how the insert or update algorithm works.

**Comment by haitham-reda** [comment]
I have a problem with multiple remote relationships issue #250 for the same reason, any advice ?

**Comment by oliland** [comment]
@haitham-reda Your issue appears to be completely unrelated. This pull request deals with all insertions from fetch requests blocking the main thread.

**Comment by oliland** [comment]
Closing because it seems to crash things and that's probably bad

**Pull request closed without merging**
