### PR TITLE
Fixed: attempt to establish a relationship between objects in different contexts

### PR DESCRIPTION
**Pull request by pitiphong-p**
In the

```
- (id)executeSaveChangesRequest:(NSSaveChangesRequest *)saveChangesRequest
                    withContext:(NSManagedObjectContext *)context
                          error:(NSError *__autoreleasing *)error
```

You have set managed object relationship across contexts. which cause the exception.

For more information, please look at #102

### CODE REVIEW

**Comment by HiDeoo** [comment]
Thanks @pitiphong-p , run into this issue today !

**Comment by conradev** [comment]
This code needs to be updated for the new method of obtaining resource identifiers. (see #82)

**Comment by pitiphong-p** [comment]
Thank you @conradev for the point.
Update the code in 1bbca5b8708194d62f8eb8ff2c545a61e1421e75

**Comment by mattt** [comment]
Thanks @pitiphong-p  and @adamhowardprice  for your fixes on this patch. I merged this in with 10bb56948ea203f5a6882d75643ec57c4a800c20, which did a bit of refactoring & cleanup, ultimately renaming the method to `-updateBackingObject:withAttributeAndRelationshipValuesFromManagedObject:`.

**Pull request merged**
