### PR TITLE
Fixes an always nil context when fetching remote attributes.

### PR DESCRIPTION
**Pull request by jerryhjones**
Commit 1f82227 added weak and strong pointers to the child managed object context. Unfortunately, the strong context referenced in the success block of the HTTP request (sent for fetching remote attributes) is always nil. Because of this, the request fails to add the fetched values to an object. I commented on the commit, here. (https://github.com/AFNetworking/AFIncrementalStore/commit/1f822279e6a7096327ae56a2f65ce8e2ff36da83)

Pull request #191 seems to be related. I'm not sure if the effort to resolve the deadlock in 1f82227 was successful because of the weak/strong relationships, or because the HTTP response block was always talking to a nil context -- @mattt will have to shed some light on his thinking there.

### CODE REVIEW

**Comment by Metamogul** [comment]
I ran into the same problem and came up with a different solution - though I'm not so sure if it's any good. After have given it some thought, I didn't really understand why this `__strong` and `__weak` modifications should do the trick and prevent deadlocks. I realized, though, that the `__weak` modifier on `weakChildContext` could lead to the context being released long before it will get reassigned to `strongChildContext` within the success block, since `__weak` doesn't guarantee the survival of the object in any way. Nevertheless, `__block` was intended for exactly that purpose, and it worked for me instead of `__weak`. Any other thoughts?

**Comment by jerryhjones** [comment]
I had the exact same thought process - I'm not sure why `__weak` and `__strong` would stop the deadlock. I'm also not sure what the solution _should_ be. Part of the reason I commented on the commit where this change took place before submitting a pull request was because I thought it might be helpful if @mattt could shed some light on his thought process.

**Comment by zsiegel** [comment]
Testing out various examples on my own I was able to deadlock the contexts so I can also reproduce that as well. 

I am still wondering why the contexts even need to be __weak and __strong but I could be missing something in the greater context of things.

**Comment by Metamogul** [comment]
After refreshing my knowledge of CoreData concurrency and nested contexts, I gave debugging this deadlock mess another round, and I might have identified a serious issue: When carefully formatting the kinda messy and uncommented AFIS code of `newValueForRelationship:...`, I stumbled upon the following messages enclosing the contexts `save:` operations, whose benefit I somehow didn't get before:

``` obj-c
id observer = [[NSNotificationCenter defaultCenter] addObserverForName:NSManagedObjectContextDidSaveNotification object:strongChildContext queue:[NSOperationQueue mainQueue] usingBlock:^(NSNotification *note) {
                            [context mergeChangesFromContextDidSaveNotification:note];
                        }];

                        // ... Saving of backing context and child context done here ...

                        [[NSNotificationCenter defaultCenter] removeObserver:observer];
```

What happens here is that `context` will have any changes from `strongChildContext` merged in, as soon as `strongChildContext` is done saving. However, merging changes this way from one context into another is deprecated when using nested contexts, as outlined in [this quick info post](http://www.cocoanetics.com/2012/07/multi-context-coredata/) on the benefits and possible usage schemes for nested MOCs. The mentioned code, which I therefore consider as unnecessary and possibly even dangerous, might lead to more than one issue:
1. I'm not sure if merging changes twice could lead to crashes and collisions, since saving a child context already automatically pushes the changes to the parent, merging them in. Most probably nothing would happen at all, since the changes are already in place - but we shouldn't just rely on possibilities. At least, a safe but unnecessary operation could cut down on AFIS overall performance.
2. Furthermore this might imperil thread/queue safety, since it's not guaranteed, that `context` is running on the main queue and not on some private queue via `NSPrivateQueueConcurrencyType`.

Anyway, commenting out the lines of code in question, I don't seem to hit any more deadlocks. At least, the amount of deadlocks occurring during tests with my testing app seems to have substantially diminished. I've already seen this in an older temporary fix of the deadlock issue I can't find atm, but back then I didn't get the reason for cutting out these lines of code. Now, I think I have learned and can state that removing them would definitely improve stability and decrease the number of deadlocks produced by AFIS.

Would do you think? I consider my self not to be the most experienced CoreData developer, so I'm interested in your opinions on that before I hastily issue a pull request.

**Comment by zsiegel** [comment]
To @Metamogul points above I have also tried this out and it seems to work. I have a test setup with relationships and partial updates of objects and I seem to get all of the appropriate change notifications as well as full proper updates.

I know alot has changed between iOS5 and iOS6 with CoreData. So far I have only tested on iOS6 so we would need to test this out on iOS5 as well.

All changes so far here seem to be valid and improve the situation.

**Comment by mattt** [comment]
Thanks, @jerryhjones.

**Pull request merged**
