### PR TITLE
Fix documentation typo and remove redundant notification

### PR DESCRIPTION
**Pull request by followben**
Just a bit of housekeeping - found a (one char!) typo in the new docs, which are excellent and a great help btw!

Also, unless I'm missing something, I don't believe the fetch request context needs to merge changes from it's direct children via notifications, as Core Data should do that automatically.

### CODE REVIEW

**Comment by mattt** [comment]
Core Data _should_ do that automatically, but it didn't without doing this manually. Unless I'm mistaken. Can you check your change against the example projects to see if everything functions as expected?

**Comment by followben** [comment]
Hey @matt - indeed, I rechecked both the basic and twitter example projects this morning on this branch, and they're both working as expected :)

**Comment by mattt** [comment]
Cool cool. Thanks again for that. This is all starting to come together, I think.

I think I've reached a breakthrough as far as write operations, so I hope to push something for that in the next day or two.

**Comment by followben** [comment]
Nice one, @mattt. First release of the app I'm using AFIS in is only pulling back info from a REST API. Next phase will have a whole bunch of POSTs and PUTs though, so looking forward to seeing what you have in mind :)

**Pull request merged**
