### PR TITLE
Inferred paths from NSPredicate relationships

### PR DESCRIPTION
**Pull request by MattNewberry**
Given the fetch request - 

```
NSFetchRequest *fetchRequest = [[NSFetchRequest alloc] initWithEntityName:@"Tracks"];
fetchRequest.predicate = [NSPredicate predicateWithFormat:@"album.id = %@", album.id];
```

return the path `/albums/(:id)/tracks`

### CODE REVIEW

**Comment by mattt** [comment]
Thanks for your patch, @MattNewberry. This is an interesting idea, but the implementation is rather brittle, since it relies on a specific predicate format pattern. My intention with the original design was for the user to implement this logic in the `-requestForFetchRequest:withContext:` method, using `NSExpression` to extract the necessary components and handle routing according the specific needs of the application.

Yours is a great example of how one might implement that, but it's a little too specific to be incorporated as a core feature.

**Comment by MattNewberry** [comment]
No problem! This works great for me and wanted to share.

**Comment by davidbitton** [comment]
@mattt, can you post an example of what @MattNewberry is doing but in the `-requestForFetchRequest:withContext` method? Thanks!

**Comment by mattt** [comment]
@davidbitton It's pretty much copy-paste from one method into the other for your particular `AFRESTClient` subclass.

**Comment by ryan-lang** [comment]
Sorry to resurrect an old topic, but I was hoping for some clarification on this.  @MattNewberry, looking at your fork - you've taken out all references to this.  Have you found that there's a better way now?

**Pull request closed without merging**
