### PR TITLE
Correct crash in "Twitter Client"/App.net example

### PR DESCRIPTION
**Pull request by f1fe**
In the `AppDotNetAPIClient`, override 
`- (id)representationOrArrayOfRepresentationsOfEntity:(NSEntityDescription *)entity fromResponseObject:(id)responseObject`

because all App.Net responses are wrapped in a "data" dictionary. Without this change, the example crashes.

### CODE REVIEW

**Comment by jghazarian** [comment]
This tripped me up when trying to use the examples. Glad I stumbled upon this. Now the example works as intended.

**Comment by huguesbr** [comment]
+1 did the same fix.. I was pretty confuse... it suck when example doesn't work...

**Comment by swizzlr** [comment]
+1 I just debugged this myself @mattt this is a pia bug with a simple fix, please merge.

**Comment by mattt** [comment]
Sorry for the delay. Thanks for sending the patch, @f1fe.

**Pull request merged**
