### PR TITLE
Update AFIncrementalStore for AFNetworking 2.0.0-RC2 support

### PR DESCRIPTION
**Pull request by Nitewriter**
The following issues have been resolved:
- Compiler issues related to 'OS_OBJECT_USE_OBJC' flag defaulting to 0 in SDK targets below iOS 6.0. 
- Depreciated uses of AFHTTPClient method 'requestWithMethod:path:parameters:' migrated to 'requestWithMethod:URLString:parameters'
- All example targets updated to work with AFNetworking 2.0.0-RC2

### CODE REVIEW

**Comment by andrewtheis** [comment]
+1 For this. Would like to use AFNetworking 2.0!!

**Comment by paddev** [comment]
when i delete a news in back office, json is modify but the object in entity is not delete!
help me please

**Comment by mattt** [comment]
As of e8c6472bf42f763d77e5c5ca584099abd555f906, AFIncrementalStore is no longer being actively maintained. Thank you for your contributions; my sincere apologies for any inconvenience this may have caused.

**Comment by proger** [comment]
indeed it's time, thanks for all the fish :)

**Pull request closed without merging**
